name: Github Activity - README

on:
  schedule:
    - cron: '*/58 * * * *'
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create README.md
        uses: actions-js/profile-readme@master
        with:
          username: bhandarisaurav
          template: ./TEMPLATE.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: ':zap: Updated README with the recent activity'
          author_name: bhandarisaurav
          github_token: ${{ secrets.GITHUB_TOKEN }}
